#!/usr/bin/env python3
"""Summarise a rendered measurement sweep into a readable Markdown table.

The summary is generated from the evidence file rather than typed by hand, so a
reader can regenerate it and get the same table, and so no claim in the summary
can drift away from the measurement it describes.

    python3 qa/interaction/summarize_sweep.py
    python3 qa/interaction/summarize_sweep.py --check   # verify it is current
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
EVIDENCE = ROOT / "qa" / "interaction" / "evidence" / "rendered-sweep-2026-08-20.json"
SUMMARY = ROOT / "qa" / "interaction" / "evidence" / "RENDERED_SWEEP_SUMMARY.md"


def width_of(viewport: str) -> int:
    return int(viewport.split("x")[0])


def build(data: dict) -> str:
    records = data["records"]
    layout = [r for r in records if r["sweep"]["probe"] == "layout"]
    enhancement = [r for r in records if r["sweep"]["probe"] == "enhancement"]
    viewports = sorted({r["sweep"]["viewport"] for r in records}, key=width_of, reverse=True)

    lines: list[str] = []
    lines.append("# Rendered sweep summary")
    lines.append("")
    lines.append("Generated by `qa/interaction/summarize_sweep.py` from")
    lines.append("`qa/interaction/evidence/rendered-sweep-2026-08-20.json`. Do not edit by hand.")
    lines.append("")
    lines.append(f"- Records: **{data['recordCount']}** ({len(layout)} layout, {len(enhancement)} enhancement)")
    lines.append(f"- Routes: **{len(data['routes'])}** · Viewports: **{len(data['viewports'])}**")
    lines.append(f"- Records that failed their own verdict set: **{data['failureCount']}**")
    lines.append("")
    lines.append(f"> **Boundary.** {data['boundary']}")
    lines.append("")

    lines.append("## Map layout by viewport width")
    lines.append("")
    lines.append("The 1101/1100 pair is the exact boundary the independent review named as a")
    lines.append("deterministic collision risk. Rows are counted from measured node positions.")
    lines.append("")
    lines.append("| Viewport | Family rows | Family nodes | Stacking faults | Node collisions | Page overflow (px) | Focus fields |")
    lines.append("| --- | ---: | ---: | ---: | ---: | ---: | ---: |")
    for viewport in viewports:
        record = next(
            (r for r in layout if r["sweep"]["viewport"] == viewport and r["sweep"]["route"] == "/map/"),
            None,
        )
        if not record:
            continue
        map_data = record.get("map", {})
        collisions = (
            len(map_data.get("familyNodeCollisions", []))
            + len(map_data.get("recordCollisions", []))
            + len(map_data.get("bandCollisions", []))
        )
        lines.append(
            f"| {viewport} | {map_data.get('familyGridRows', 0)} | {map_data.get('familyNodeCount', 0)} | "
            f"{len(map_data.get('stackingFaults', []))} | {collisions} | {record.get('horizontalOverflow', 0)} | "
            f"{map_data.get('focusFieldCount', 0)} |"
        )
    lines.append("")

    lines.append("## Every route, every viewport")
    lines.append("")
    lines.append("A cell shows the number of records that failed at that route and width.")
    lines.append("")
    header = "| Route | " + " | ".join(viewports) + " |"
    lines.append(header)
    lines.append("| --- |" + " ---: |" * len(viewports))
    for route in data["routes"]:
        cells = []
        for viewport in viewports:
            matching = [
                r for r in records if r["sweep"]["route"] == route and r["sweep"]["viewport"] == viewport
            ]
            failed = sum(1 for r in matching if not r["pass"])
            cells.append("—" if not matching else ("0" if failed == 0 else f"**{failed}**"))
        lines.append(f"| `{route}` | " + " | ".join(cells) + " |")
    lines.append("")

    lines.append("## Contracts asserted per record")
    lines.append("")
    verdict_keys: dict[str, int] = {}
    for record in records:
        for key, value in record.get("verdict", {}).items():
            verdict_keys.setdefault(key, 0)
            if value:
                verdict_keys[key] += 1
    lines.append("| Contract | Records asserting it | Records passing |")
    lines.append("| --- | ---: | ---: |")
    for key in sorted(verdict_keys):
        total = sum(1 for r in records if key in r.get("verdict", {}))
        lines.append(f"| `{key}` | {total} | {verdict_keys[key]} |")
    lines.append("")

    lines.append("## Reproducing this sweep")
    lines.append("")
    lines.append("1. `cd site && npm run build && node serve.mjs`")
    lines.append("2. Copy `qa/interaction/layout-probe.js`, `enhancement-probe.js`, and")
    lines.append("   `layout-sweep-driver.js` into `site/dist/assets/`, and add a module script tag")
    lines.append("   for the driver to each generated page. These are local instruments; they are")
    lines.append("   never part of a committed build.")
    lines.append("3. Set the browser viewport, then run `patternMapSweep.start({...})` per the")
    lines.append("   driver's own usage note, collecting results at a local endpoint.")
    lines.append("4. Rebuild with `npm run build` to discard the injection before committing.")
    lines.append("")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the summary is out of date")
    args = parser.parse_args()

    data = json.loads(EVIDENCE.read_text())
    rendered = build(data)

    if args.check:
        if not SUMMARY.exists() or SUMMARY.read_text() != rendered:
            print("FAIL rendered sweep summary is out of date; run qa/interaction/summarize_sweep.py")
            return 1
        print("PASS rendered sweep summary matches its evidence file")
        return 0

    SUMMARY.write_text(rendered)
    print(f"wrote {SUMMARY.relative_to(ROOT)} ({data['recordCount']} records, {data['failureCount']} failures)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
